# Generated by Django 2.0.6 on 2018-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionCostoProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSuelo', models.CharField(max_length=30)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sistemaDrenaje', models.CharField(max_length=20)),
                ('plagas', models.CharField(max_length=20)),
                ('deshoje', models.CharField(max_length=20)),
                ('embolse', models.CharField(max_length=20)),
                ('lvlMar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pluviosidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('luminosidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('densidadSiembra', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
