# Generated by Django 2.0.6 on 2018-06-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        ('simulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacioncostoproduccion',
            name='usuarioSim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.usuario'),
        ),
    ]
