# Generated by Django 2.0.6 on 2018-06-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_produccion_cosecha'),
        ('simulacion', '0002_simulacioncostoproduccion_usuariosim'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacioncostoproduccion',
            name='cosecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.Cosecha'),
        ),
    ]
