# Generated by Django 2.0.6 on 2018-06-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0003_simulacioncostoproduccion_cosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacioncostoproduccion',
            name='fechaSim',
            field=models.DateField(null=True),
        ),
    ]
