# Generated by Django 2.0.6 on 2018-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alturaPlanta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grosorTallo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numeroHojas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pesoRacimo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoHectarea', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kgCosechados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioKg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utilidadEsperada', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
